#ifndef WXD_DC_CONSTANTS_H
#define WXD_DC_CONSTANTS_H

// Background mode constants
#define WXD_TRANSPARENT 0
#define WXD_SOLID 1

// Pen Style Constants
#define WXD_PENSTYLE_SOLID 0
#define WXD_PENSTYLE_DOT 1
#define WXD_PENSTYLE_LONG_DASH 2
#define WXD_PENSTYLE_SHORT_DASH 3
#define WXD_PENSTYLE_DOT_DASH 4
#define WXD_PENSTYLE_TRANSPARENT 5
#define WXD_PENSTYLE_STIPPLE 6
#define WXD_PENSTYLE_USER_DASH 7
#define WXD_PENSTYLE_BDIAGONAL_HATCH 8
#define WXD_PENSTYLE_CROSSDIAG_HATCH 9
#define WXD_PENSTYLE_FDIAGONAL_HATCH 10
#define WXD_PENSTYLE_CROSS_HATCH 11
#define WXD_PENSTYLE_HORIZONTAL_HATCH 12
#define WXD_PENSTYLE_VERTICAL_HATCH 13

// Brush Style Constants
#define WXD_BRUSHSTYLE_SOLID 0
#define WXD_BRUSHSTYLE_TRANSPARENT 1
#define WXD_BRUSHSTYLE_BDIAGONAL_HATCH 2
#define WXD_BRUSHSTYLE_CROSSDIAG_HATCH 3
#define WXD_BRUSHSTYLE_FDIAGONAL_HATCH 4
#define WXD_BRUSHSTYLE_CROSS_HATCH 5
#define WXD_BRUSHSTYLE_HORIZONTAL_HATCH 6
#define WXD_BRUSHSTYLE_VERTICAL_HATCH 7
#define WXD_BRUSHSTYLE_STIPPLE 8
#define WXD_BRUSHSTYLE_STIPPLE_MASK_OPAQUE 9
#define WXD_BRUSHSTYLE_STIPPLE_MASK 10

#endif // WXD_DC_CONSTANTS_H 