/* This is a new file */
//! Safe wrapper for wxFontPickerCtrl.

use crate::base::{Point, Size};
use crate::event::WxEvtHandler;
use crate::font::Font; // Import the safe Font wrapper
use crate::window::Window;
use crate::WxWidget;
use std::ffi::c_long;
use std::ptr;
use wxdragon_sys as ffi;

// --- Constants for wxFontPickerCtrl ---
// These constants are typically defined in wx/fontpicker.h for wxFontPickerCtrl
// For now, assuming they will be generated by const_extractor and available via wxdragon_sys
// e.g., ffi::WXD_FNTP_DEFAULT_STYLE, etc.
pub const FNTP_DEFAULT_STYLE: i64 = ffi::WXD_FNTP_DEFAULT_STYLE;
pub const FNTP_USE_TEXTCTRL: i64 = ffi::WXD_FNTP_USE_TEXTCTRL;
pub const FNTP_FONTDESC_AS_LABEL: i64 = ffi::WXD_FNTP_FONTDESC_AS_LABEL;
pub const FNTP_USEFONT_FOR_LABEL: i64 = ffi::WXD_FNTP_USEFONT_FOR_LABEL;

// --- FontPickerCtrl ---

#[derive(Clone)]
pub struct FontPickerCtrl {
    window: Window, // Embed Window
}

impl FontPickerCtrl {
    /// Creates a new FontPickerCtrlBuilder.
    pub fn builder<'a>(parent: &'a impl WxWidget) -> FontPickerCtrlBuilder<'a> {
        let mut builder = FontPickerCtrlBuilder::default();
        builder.parent_ptr = parent.handle_ptr();
        builder
    }

    /// Gets the currently selected font.
    /// Returns `None` if no font is selected or the font is invalid.
    pub fn get_selected_font(&self) -> Option<Font> {
        unsafe {
            let font_ptr = ffi::wxd_FontPickerCtrl_GetSelectedFont(
                self.window.as_ptr() as *mut ffi::wxd_FontPickerCtrl_t
            );
            if font_ptr.is_null() {
                None
            } else {
                // Font::from_ptr should take ownership (true) and handle drop via wxd_Font_Destroy
                Some(Font::from_ptr(font_ptr, true))
            }
        }
    }

    /// Sets the currently selected font.
    pub fn set_selected_font(&self, font: &Font) {
        unsafe {
            ffi::wxd_FontPickerCtrl_SetSelectedFont(
                self.window.as_ptr() as *mut ffi::wxd_FontPickerCtrl_t,
                font.as_ptr(), // Font::as_ptr() should provide const wxd_Font_t*
            );
        }
    }

    /// Creates a FontPickerCtrl from a raw pointer.
    /// # Safety
    /// The pointer must be a valid `wxd_FontPickerCtrl_t`.
    unsafe fn from_ptr(ptr: *mut ffi::wxd_FontPickerCtrl_t) -> Self {
        FontPickerCtrl {
            window: Window::from_ptr(ptr as *mut ffi::wxd_Window_t),
        }
    }
}

impl WxWidget for FontPickerCtrl {
    fn handle_ptr(&self) -> *mut ffi::wxd_Window_t {
        self.window.handle_ptr()
    }
}

impl WxEvtHandler for FontPickerCtrl {
    unsafe fn get_event_handler_ptr(&self) -> *mut ffi::wxd_EvtHandler_t {
        self.window.get_event_handler_ptr()
    }
}

// Drop is handled by the embedded Window or parentage.

// --- FontPickerCtrlBuilder ---

pub struct FontPickerCtrlBuilder<'a> {
    parent_ptr: *mut ffi::wxd_Window_t,
    id: i32,
    initial_font: Option<Font>, // Store Option<Font> and get its ptr in build()
    pos: Point,
    size: Size,
    style: i64,
    _phantom: std::marker::PhantomData<&'a ()>,
}

impl<'a> Default for FontPickerCtrlBuilder<'a> {
    fn default() -> Self {
        Self {
            parent_ptr: ptr::null_mut(),
            id: ffi::WXD_ID_ANY as i32,
            initial_font: None,
            pos: Point::default(),
            size: Size::default(),
            style: FNTP_DEFAULT_STYLE,
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<'a> FontPickerCtrlBuilder<'a> {
    pub fn with_id(mut self, id: i32) -> Self {
        self.id = id;
        self
    }

    pub fn with_initial_font(mut self, font: Font) -> Self {
        self.initial_font = Some(font);
        self
    }

    pub fn with_pos(mut self, pos: Point) -> Self {
        self.pos = pos;
        self
    }

    pub fn with_size(mut self, size: Size) -> Self {
        self.size = size;
        self
    }

    pub fn with_style(mut self, style: i64) -> Self {
        self.style = style;
        self
    }

    pub fn build(self) -> FontPickerCtrl {
        assert!(
            !self.parent_ptr.is_null(),
            "FontPickerCtrl requires a parent"
        );

        let initial_font_ptr = self
            .initial_font
            .as_ref()
            .map_or(ptr::null(), |f| f.as_ptr());

        let ffi_pos: ffi::wxd_Point = self.pos.into();
        let ffi_size: ffi::wxd_Size = self.size.into();

        let ptr = unsafe {
            ffi::wxd_FontPickerCtrl_Create(
                self.parent_ptr,
                self.id,
                initial_font_ptr, // Pass the const wxd_Font_t*
                ffi_pos,
                ffi_size,
                self.style as c_long,
            )
        };
        if ptr.is_null() {
            panic!("Failed to create FontPickerCtrl: FFI returned null pointer.");
        } else {
            unsafe { FontPickerCtrl::from_ptr(ptr) }
        }
    }
}
