//!
//! Safe wrapper for wxNotificationMessage.

// use crate::window::Window; // For parent type, though it's just a handle - Unused, removing
// use crate::base::WxResult; // Will define locally for now
use std::ffi::{CString, NulError};
use std::os::raw::c_int;
use wxdragon_sys as ffi;
use crate::window::WxWidget; // Import WxWidget trait
// use log; // REMOVED: Using println! instead

// --- Temporary Error Handling --- TODO: Refactor to use a crate-wide error type
#[derive(Debug)]
pub enum Error {
    NulError(NulError),
    FfiCreation(String),
}

impl From<NulError> for Error {
    fn from(err: NulError) -> Self {
        Error::NulError(err)
    }
}

pub type WxResult<T> = Result<T, Error>;
// --- End Temporary Error Handling ---

// wxNotificationMessage specific constants that might be useful
// These values are from wxWidgets documentation for wxNotificationMessage::Show
pub const TIMEOUT_AUTO: i32 = -1; // Automatically determine the timeout
pub const TIMEOUT_NEVER: i32 = 0;  // Never hide the notification automatically (manual Close() needed)

// Flags for wxNotificationMessage (usually correspond to wxICON_... values)
// These are common wxWidgets flags, ensure they are available via ffi or define them if not.
// For now, assuming users will pass raw ffi::WXD_ICON_... flags.
// pub const ICON_NONE: i32 = 0; (This is usually the default)
// pub const ICON_INFORMATION: i32 = ffi::WXD_ICON_INFORMATION; (Example, assuming generated)
// pub const ICON_WARNING: i32 = ffi::WXD_ICON_WARNING; (Example)
// pub const ICON_ERROR: i32 = ffi::WXD_ICON_ERROR; (Example)

// Icon flags (assuming these will be generated by const_extractor and available in ffi)
// Note: wxICON_NONE is typically 0. If not explicitly defined by wxWidgets as a named constant
// that const_extractor picks up, users can just pass 0.
// pub const ICON_NONE: i32 = 0; // Or potentially ffi::WXD_ICON_NONE if generated

/// Use with `NotificationMessageBuilder::with_flags` to show an information icon.
/// This assumes `WXD_ICON_INFORMATION` is generated by `const_extractor`.
pub const ICON_INFORMATION: i64 = ffi::WXD_ICON_INFORMATION; // Assumed to be generated, changed to i64
/// Use with `NotificationMessageBuilder::with_flags` to show a warning icon.
/// This assumes `WXD_ICON_WARNING` is generated by `const_extractor`.
pub const ICON_WARNING: i64 = ffi::WXD_ICON_WARNING; // Assumed to be generated, changed to i64
/// Use with `NotificationMessageBuilder::with_flags` to show an error icon.
/// This assumes `WXD_ICON_ERROR` is generated by `const_extractor`.
pub const ICON_ERROR: i64 = ffi::WXD_ICON_ERROR; // Assumed to be generated, changed to i64
/// Use with `NotificationMessageBuilder::with_flags` to show a question icon.
/// This assumes `WXD_ICON_QUESTION` is generated by `const_extractor`.
pub const ICON_QUESTION: i64 = ffi::WXD_ICON_QUESTION; // Assumed to be generated, changed to i64

/// Represents a `wxNotificationMessage`.
///
/// This struct manages a pointer to the underlying C++ `wxNotificationMessage` object.
/// It is responsible for calling `wxd_NotificationMessage_Destroy` when it goes out of scope.
#[derive(Debug)] // wxNotificationMessage is not Cloneable as it has direct destructor
pub struct NotificationMessage {
    ptr: *mut ffi::wxd_NotificationMessage_t,
}

impl NotificationMessage {
    /// Creates a new `NotificationMessageBuilder`.
    pub fn builder() -> NotificationMessageBuilder {
        NotificationMessageBuilder::new()
    }

    /// Shows the notification to the user.
    ///
    /// # Arguments
    /// * `timeout` - How long the notification is shown, in seconds.
    ///   Use `TIMEOUT_AUTO` to let the system decide, or `TIMEOUT_NEVER` if it shouldn't time out.
    ///   A positive value specifies the timeout in seconds.
    ///
    /// Returns `true` if it was possible to show the notification, `false` if an error occurred.
    pub fn show(&self, timeout: i32) -> bool {
        unsafe { ffi::wxd_NotificationMessage_Show(self.ptr, timeout as c_int) }
    }

    /// Hides the notification.
    ///
    /// Returns `true` if the notification was hidden or `false` if it couldn't be (e.g. it was already hidden).
    pub fn close(&self) -> bool {
        unsafe { ffi::wxd_NotificationMessage_Close(self.ptr) }
    }

    /// Sets the main text of the notification.
    /// Returns `true` on success.
    pub fn set_title(&self, title: &str) -> WxResult<()> {
        let c_title = CString::new(title)?;
        unsafe {
            ffi::wxd_NotificationMessage_SetTitle(self.ptr, c_title.as_ptr());
        }
        Ok(())
    }

    /// Sets the secondary, more detailed, text of the notification.
    /// Returns `true` on success.
    pub fn set_message(&self, message: &str) -> WxResult<()> {
        let c_message = CString::new(message)?;
        unsafe {
            ffi::wxd_NotificationMessage_SetMessage(self.ptr, c_message.as_ptr());
        }
        Ok(())
    }

    /// Sets the flags for the notification message.
    /// These flags typically control the icon shown.
    /// Returns `true` on success.
    pub fn set_flags(&self, flags: i32) -> WxResult<()> {
        unsafe {
            ffi::wxd_NotificationMessage_SetFlags(self.ptr, flags as c_int);
        }
        Ok(())
    }

    /// Sets the parent window for this notification.
    /// Returns `true` on success.
    pub fn set_parent<W: WxWidget>(&self, parent: Option<&W>) -> WxResult<()> {
        let parent_ptr = parent.map_or(std::ptr::null_mut(), |p| p.handle_ptr());
        unsafe {
            ffi::wxd_NotificationMessage_SetParent(self.ptr, parent_ptr);
        }
        Ok(())
    }
    
    /// Adds an action button to the notification.
    ///
    /// This method should be called after the `NotificationMessage` has been created
    /// but before `show()` is called for the actions to appear.
    /// The `action_id` will be returned by `event.get_id()` if the corresponding
    /// action button is clicked and an `EventType::NotificationMessageAction` is caught.
    ///
    /// # Arguments
    /// * `action_id` - An integer ID for this action. Must be > 0.
    /// * `label` - The text to display on the action button.
    ///
    /// Returns `true` if the action was added successfully, `false` otherwise (e.g., too many actions).
    pub fn add_action(&self, action_id: i32, label: &str) -> WxResult<bool> {
        if self.ptr.is_null() {
            return Err(Error::FfiCreation("NotificationMessage pointer is null".to_string()));
        }
        if action_id <= 0 {
            // wxWidgets requires action IDs to be > 0
            // Consider returning a specific error type here
            println!("Warning: NotificationMessage action_id must be > 0.");
            return Ok(false); 
        }
        let c_label = CString::new(label)?; // This can return NulError, which converts to Error::NulError
        let result = unsafe {
            ffi::wxd_NotificationMessage_AddAction(self.ptr, action_id, c_label.as_ptr())
        };
        Ok(result)
    }

    // Note: wxNotificationMessage also supports AddAction, but this is not yet in the C API.
}

impl Drop for NotificationMessage {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe {
                ffi::wxd_NotificationMessage_Destroy(self.ptr);
            }
            // self.ptr = std::ptr::null_mut(); // Not strictly necessary as it's being dropped
        }
    }
}

/// Builder for `NotificationMessage` instances.
#[derive(Default)]
pub struct NotificationMessageBuilder {
    title: String,
    message: String,
    parent: Option<*mut ffi::wxd_Window_t>,
    flags: i32, // Default is typically 0 (wxICON_NONE or similar)
}

impl NotificationMessageBuilder {
    /// Creates a new builder with default values.
    pub fn new() -> Self {
        NotificationMessageBuilder {
            title: String::new(),
            message: String::new(),
            parent: None,
            flags: 0, // Assuming 0 is a sensible default (e.g. no icon)
        }
    }

    /// Sets the main title of the notification.
    pub fn with_title(mut self, title: &str) -> Self {
        self.title = title.to_string();
        self
    }

    /// Sets the detailed message of the notification.
    pub fn with_message(mut self, message: &str) -> Self {
        self.message = message.to_string();
        self
    }

    /// Sets the parent window.
    pub fn with_parent<W: WxWidget>(mut self, parent: &W) -> Self {
        self.parent = Some(parent.handle_ptr());
        self
    }

    /// Sets the flags (e.g., for icons like `ICON_INFORMATION`).
    pub fn with_flags(mut self, flags: i64) -> Self {
        self.flags = flags as i32;
        self
    }

    /// Builds the `NotificationMessage`.
    ///
    /// Returns `Some(NotificationMessage)` on success, or `None` if creation failed.
    pub fn build(self) -> WxResult<NotificationMessage> {
        let c_title = CString::new(self.title)?;
        let c_message = CString::new(self.message)?;
        let parent_ptr = self.parent.unwrap_or(std::ptr::null_mut());

        let ptr = unsafe {
            ffi::wxd_NotificationMessage_Create(
                c_title.as_ptr(),
                c_message.as_ptr(),
                parent_ptr,
                self.flags as c_int,
            )
        };

        if ptr.is_null() {
            Err(Error::FfiCreation("wxd_NotificationMessage_Create returned null".to_string()))
        } else {
            Ok(NotificationMessage { ptr })
        }
    }
}

// Ensure `Window` has `handle_ptr` and `AsRef<Window>` can be used.
// This implies that `crate::window::Window` struct is accessible and has `handle_ptr()` method.
// And that `WxWidget` trait (which provides `handle_ptr`) is implemented by `Window` if `Window` itself is a trait.
// Given `Window` is likely a struct wrapper, `AsRef<Window>` would work if `W` is `Window` or `&Window`. 